# Generated by Django 4.2 on 2026-04-24 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField()),
                ("genre", models.CharField(max_length=100)),
                ("release_date", models.DateField()),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="movies/"),
                ),
                (
                    "rating",
                    models.DecimalField(decimal_places=1, default=0, max_digits=3),
                ),
                ("duration", models.IntegerField(help_text="Duration in minutes")),
                ("director", models.CharField(max_length=200)),
                ("cast", models.TextField(help_text="Comma-separated list of actors")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Movies",
                "ordering": ["-release_date"],
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, unique=True)),
                ("content", models.TextField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="news/")),
                ("author", models.CharField(default="Admin", max_length=200)),
                ("published_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("is_featured", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "News",
                "ordering": ["-published_date"],
            },
        ),
        migrations.CreateModel(
            name="Slider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("image", models.ImageField(upload_to="slider/")),
                ("link_url", models.URLField(blank=True, null=True)),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Order of appearance in slider"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Trailer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("video_url", models.URLField()),
                (
                    "thumbnail",
                    models.ImageField(blank=True, null=True, upload_to="trailers/"),
                ),
                (
                    "duration",
                    models.IntegerField(default=0, help_text="Duration in seconds"),
                ),
                ("uploaded_date", models.DateTimeField(auto_now_add=True)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trailers",
                        to="app.movie",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_date"],
            },
        ),
    ]
