# Generated by Django 4.2 on 2026-05-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_advertisement_celebrity_newslettersubscriber_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovieTheater",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=20)),
                ("img_src", models.CharField(max_length=200)),
                ("img_width", models.IntegerField()),
                ("img_height", models.IntegerField()),
                ("anchor_url", models.CharField(max_length=200)),
                ("movie_genre", models.CharField(max_length=10)),
                ("movie_title", models.CharField(max_length=20)),
                ("lower_rating", models.CharField(max_length=5)),
                ("upper_rating", models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name="MovieTV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=20)),
                ("img_src", models.CharField(max_length=200)),
                ("img_width", models.IntegerField()),
                ("img_height", models.IntegerField()),
                ("anchor_url", models.CharField(max_length=200)),
                ("movie_genre", models.CharField(max_length=10)),
                ("movie_title", models.CharField(max_length=20)),
                ("lower_rating", models.CharField(max_length=5)),
                ("upper_rating", models.CharField(max_length=5)),
            ],
            options={
                "verbose_name": "Movie TV",
                "verbose_name_plural": "Movies TV",
            },
        ),
    ]
